SELECT * FROM sales.sales;
-- Total Revenue Generated by Male and Female Employees
SELECT Gender, SUM(Purchase_Amount) as Revenue
FROM sales group by Gender;

-- Average Purchase Amount;

SELECT AVG(Purchase_Amount) FROM sales;

-- Customers got Discount but still spent more than average purchase amount

SELECT ï»¿Customer_ID, Purchase_Amount FROM sales 
WHERE Discount_Applied = "Yes" and Purchase_Amount >= (Select AVG(Purchase_Amount) From sales);

-- Total Number of Male Customers and Female Customers

SELECT Gender, COUNT(*) FROM sales group by Gender;

USE sales;
-- Which are the top 5 products with the highest average review rating?

SELECT Item_Purchased, ROUND(AVG(Review_Rating),2) as "Average_Review_Rating" 
FROM sales
group by Item_Purchased 
order by Avg(Review_Rating) desc limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT Shipping_Type, round(AVG(Purchase_Amount),2) 
from sales
WHERE Shipping_Type in('Standard', 'Express')
GROUP BY Shipping_Type;

-- Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM sales
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT ï»¿Customer_ID, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM sales)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- What are the top 3 most purchased products within each category? 

WITH Item_Count AS (
SELECT Category, Item_Purchased,
COUNT(ï»¿Customer_ID) AS Total_orders,
row_number() OVER (PARTITION BY category ORDER BY COUNT(ï»¿Customer_ID) DESC) AS Item_Rank
from sales
GROUP BY category, item_purchased
) 
SELECT item_rank,category, item_purchased, total_orders
FROM Item_Count
WHERE item_rank <=3;
 
 -- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 
SELECT Subscription_Status,
       COUNT(ï»¿Customer_ID) AS repeat_buyers
FROM sales
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

-- What is the revenue contribution of each age group? 
SELECT 
    Age,
    SUM(Purchase_Amount) AS total_revenue
FROM sales
GROUP BY Age
ORDER BY Total_Revenue desc;

 
